### ISSUE TITLE
CORS policy

### ISSUE THREAD

**Issue by QwaserLi** [na-ji/node-manga-parser#3]
I'm trying to re-create a app similar to tachiyomi as a side project. And I get this when trying to use the library: 

![image](https://user-images.githubusercontent.com/40726675/44619232-31b23e00-a8d7-11e8-94d4-9ebafb71facd.png)

I found a slight work around by using a chrome extension the issue is that, without the extension I wouldn't be able to get it working on mobile. Just curious if you were aware of this?

**Comment by na-ji** [comment]
Hello!

The library is made for server usage, where there is no CORS policy. In the browser, you cannot bypass the CORS policy without an extension. Sorry.
